# GitHub Actions Workflow for CI/CD Pipeline

# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      # - name: Run tests
      #  run: npm test

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: |
          npx expo prebuild
          npx expo build:android --non-interactive --no-wait --output-dir=build/android
          npx expo build:ios --non-interactive --no-wait --output-dir=build/ios

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: |
            build/android/*.apk
            build/ios/*.ipa
